### ISSUE TITLE
Users should be able to specify bee node API and debug API URLs

### ISSUE THREAD

**Issue by vojtechsimetka** [ethersphere/bee-status#3]
Currently the status app assumes the default APIs - `localhost:1633` & `:1635` . It should allow changing this URL e.g. directly in the first step of the Node Setup through a button. or maybe in the Settings page?

![Screenshot 2021-03-07 at 16 59 59](https://user-images.githubusercontent.com/7974813/110246160-c8f7b200-7f66-11eb-8e76-17771261d17a.png)

**Comment by matmertz25** [comment]
Right now these endpoints are derived from the environment variables in `.env` files. I agree I would like some mechanism to dynamically change urls. Not sure how to best handle this in the UI yet because I think it should be handled differently depending upon how want to package it. 

Local Standalone: Set env variables when building / serving frontend

Local Standalone: Set env variables when building / serving frontend
Electron Installed App: Use the filesystem API to directly read the configuration file and retrieve from there.

**Comment by matmertz25** [comment]
0c05c06 dynamic api and debug api URLs

**Comment by matmertz25** [comment]
Can change host on both node setup and in the settings section. Also allows for specifying https://gateway.ethswarm.org/ as the file API to interact directly with that.

![image](https://user-images.githubusercontent.com/40722304/110411822-308e2a00-8059-11eb-83c5-5f5afa8c0447.png)


![image](https://user-images.githubusercontent.com/40722304/110411669-fc1a6e00-8058-11eb-8ba2-a77360093900.png)

**Comment by matmertz25** [comment]
resolved in #1
